name = "ryu_fortran"
version = "0.1.0"
license = "license"
author = "Jane Doe"
maintainer = "jane.doe@example.com"
copyright = "Copyright 2022, Jane Doe"
[build]
auto-executables = true
auto-examples = true
[install]
library = false
[[test]]
name = "test-roundtrip"
source-dir = "test/test_roundtrip"
main = "tester.f90"