name = "ryu_fortran"
version = "0.1.0"
license = "license"
maintainer = "St Maxwell"

[build]
auto-executables = true

[dev-dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive.git"

[[test]]
name = "test-f2shortest"
source-dir = "test/test_f2shortest"
main = "tester.f90"

[[test]]
name = "test-d2shortest"
source-dir = "test/test_d2shortest"
main = "tester.f90"

[[test]]
name = "test-d2exp"
source-dir = "test/test_d2exp"
main = "tester.f90"

[[test]]
name = "test-d2fixed"
source-dir = "test/test_d2fixed"
main = "tester.f90"
